version: '3'
services:
  elasticsearch:
    environment:
      - discovery.type=single-node
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  postgres:
    environment:
      - POSTGRES_USER=takaro
      - POSTGRES_PASSWORD=takaro
    image: postgres:12.5
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  redis:
    image: redis:6.0.10
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  elasticsearch:
  postgres:
  redis:
